### PR TITLE
Some performance optimizations

### PR DESCRIPTION
**Pull request by safijari**
This PR gives some performance gains for normal use. The benchmark (moon) took 232 seconds on my machine. The main differences are:

- ply saving turned off in the example (I think this saves about 25 seconds)
- there were about 54 million calls to `mesh.nodes`. This isn't returning a pointer to a list it's creating a `NodeView` object or something, so it adds up. Replaced a number of these by creating the view once and reusing it, down to about 9 million now and this shaves off 8 or so seconds.
- (optional) using cython counterpart of the networkx package (155 seconds with this, 177 without). The package is called `cynetworkx` and can be pip installed but the build takes a long time because it runs in a single thread. For a faster build you can clone it and do `python setup.py build_ext -j 8` before installing.

There's one more change I didn't include: cythonizing most of the code as gives another 15 or so seconds, but I feel the added devops burden isn't worth it at this stage.

I know these gains look modest but for larger problems/resolutions they can really add up. I'm fascinated by the work you've done here and I feel a lot more can be done performance wise since most of the time is spent doing mesh operation in a single thread. If you would be willing to get on a call with me and walk me through some of the hairier parts of the code I may be able to help a lot more (e.g. the bilateral filtering can probably be made much faster through judicious use of numba, and many of the long loops may be parallelizable).

### CODE REVIEW

**Comment by safijari** [comment]
I just noticed there's a weirdly worded PR ("useless function name"). I had changed "write_ply" to "compute_ply" because I wanted to take the write part out and make a new function but I never made that change. That PR just reverses my now useless change. Apologies if it comes off as disrespectful it's not meant to be.

**Comment by LemonATsu** [comment]
> Apologies if it comes off as disrespectful it's not meant to be.
Not at all! We are grateful for your help and contribution. We are currently reviewing the PR and will get back to you later.

Again, thanks for the effort!

**Comment by jnorris441** [comment]
@safijari sorry what is `external.fast_any_all`

https://github.com/vt-vl-lab/3d-photo-inpainting/pull/7/files#diff-56f5ee4c4a68a9133188d62a4dc3b46fR3

**Comment by safijari** [comment]
Oh, that's not supposed to be there. I was trying to speed up the bilateral filter and roughly 70% of the time spent in the bilateral filter is on a numpy.any call. I was trying out a faster alterative but it didn't really work out. I can remove the import.

**Comment by safijari** [comment]
I have removed the stale import. Please let me know if there is something else you need from me :)

**Comment by victusfate** [comment]
@safijari merged in your changes to my local fork to test. Just a heads  up you need 3 map_location=torch.device(device) added to torch.load calls

**Comment by ShihMengLi** [comment]
Hi, @safijari. Sorry for the late reply. Thanks for your pull-request. We have merge it into our latest version. By the way, we set the `save_ply` flag to be `True` because some users might want to see the 
output mesh directly.

**Comment by ShihMengLi** [comment]
Hi, @safijari . Sorry for the let reply. We thank for your contribution! We have merge them into our master branch. 
By the way, we did not change the flag `save_ply` as some users might want to see the output 3-D mesh directly.

**Comment by victusfate** [comment]
about how long should cynetworkx take to install?
updating to the latest master branch now (added Cython 3.0a3 as another dependency)
and it's taking it's time

**Comment by victusfate** [comment]
My bad, tracked it down to an enum34 library issue (not sure where I got that)
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
pip uninstall -y enum34

**Pull request merged**
